// client/react/src/components/NavBar.jsx
import React from "react";
import { Link } from "react-router-dom";
import styled from "styled-components";

const NavBar = () => {
    return <NavBarWrapper>
        <Logo to="/">Demo App</Logo>
    </NavBarWrapper>;
};

const NavBarWrapper = styled.div`
    height: 64px;
    width: calc(100vw - 30px);
    padding: 0 15px;

    display: flex;
    align-items: center;
    justify-content: space-between;
`;

const Logo = styled(Link)`
    text-decoration: none;
    color: black;
    font-size: 28px;
`;

export default NavBar;

// client/vue/src/components/NavBar.vue
<template>
<div class="nav">
    <router-link to="/" class="nav-link">Demo App</router-link>
</div>
</template>

<style>
.nav {
    height: 64px;
    width: calc(100vw - 30px);
    padding: 0 15px;

    display: flex;
    align-items: center;
    justify-content: space-between;
}

.nav-link {
    text-decoration: none;
    color: black;
    font-size: 28px;
}
</style>
